apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 341552581828.dkr.ecr.ap-northeast-3.amazonaws.com/demo-frontend
  newName: 341552581828.dkr.ecr.ap-northeast-3.amazonaws.com/demo-frontend
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
